In [1]:
import cv2,os,tensorflow as tf, numpy as np
from tensorflow.python.keras.utils.data_utils import get_file

In [2]:
class_file="coco.names"
model_URL="http://download.tensorflow.org/models/object_detection/tf2/20200711/ssd_mobilenet_v2_320x320_coco17_tpu-8.tar.gz"

In [4]:
with open(class_file,'r') as f:
    class_list=f.read().splitlines()
    
class_list

['__Background__',
 'person',
 'bicycle',
 'car',
 'motorcycle',
 'airplane',
 'bus',
 'train',
 'truck',
 'boat',
 'traffic light',
 'fire hydrant',
 'street sign',
 'stop sign',
 'parking meter',
 'bench',
 'bird',
 'cat',
 'dog',
 'horse',
 'sheep',
 'cow',
 'elephant',
 'bear',
 'zebra',
 'giraffe',
 'hat',
 'backpack',
 'umbrella',
 'shoe',
 'eye glasses',
 'handbag',
 'tie',
 'suitcase',
 'frisbee',
 'skis',
 'snowboard',
 'sports ball',
 'kite',
 'baseball bat',
 'baseball glove',
 'skateboard',
 'surfboard',
 'tennis racket',
 'bottle',
 'plate',
 'wine glass',
 'cup',
 'fork',
 'knife',
 'spoon',
 'bowl',
 'banana',
 'apple',
 'sandwich',
 'orange',
 'broccoli',
 'carrot',
 'hot dog',
 'pizza',
 'donut',
 'cake',
 'chair',
 'couch',
 'potted plant',
 'bed',
 'mirror',
 'dining table',
 'window',
 'desk',
 'toilet',
 'door',
 'tv',
 'laptop',
 'mouse',
 'remote',
 'keyboard',
 'cell phone',
 'microwave',
 'oven',
 'toaster',
 'sink',
 'refrigerator',
 'blender',
 'book',
 'cloc

In [5]:
color_list=np.random.uniform(0,255,(len(class_list)))
color_list

array([ 84.14223666, 153.2815052 , 251.75114366, 133.84723148,
        17.17284584,  94.58525554,  46.6922098 , 232.03337749,
       186.91306628, 172.1952391 , 210.39448206,   4.34781953,
        63.49266956,  35.3667816 , 161.18117547,  38.97072803,
       230.2174155 ,  22.15100054, 250.13844401,  60.72561992,
        63.83883576,  43.02175145, 124.29052006,  18.66288286,
        92.440516  , 125.74252758, 245.97310821,  77.36424214,
        97.88112643, 230.95984495,  59.01617169, 110.84231215,
        46.48293668, 143.01227406,  59.38917206, 235.44548379,
       104.83915956, 130.2582116 , 127.0964876 , 215.50648259,
        92.05955834, 198.6528133 , 192.48774275,  64.05986949,
        96.70976433, 124.4759649 ,  29.44054237, 114.17363595,
        65.96903228, 110.25712561, 234.70558629,  87.17857351,
        97.12842697,  74.79762416, 209.61614033, 102.1381953 ,
        86.6311587 ,  55.2323142 , 156.87364766,  89.46470858,
        45.01026022, 117.46693986, 227.47939776,  43.12

In [6]:
len(class_list),len(color_list)

(92, 92)

In [7]:
model_file=os.path.basename(model_URL)
model_file

'ssd_mobilenet_v2_320x320_coco17_tpu-8.tar.gz'

In [11]:
model_name=model_file[:-7]
model_name

'ssd_mobilenet_v2_320x320_coco17_tpu-8'

In [12]:
models_dir="./pretrained_models"
os.makedirs(models_dir,exist_ok=True)

In [13]:
#download model
get_file(fname=model_file,origin=model_URL,cache_dir=models_dir,cache_subdir="checkpoints",extract=True)

46047232/46042990 [==============================] - 3s 0us/step


'./pretrained_models\\checkpoints\\ssd_mobilenet_v2_320x320_coco17_tpu-8.tar.gz'

In [14]:
tfod_model=tf.saved_model.load(os.path.join(models_dir,"checkpoints",model_name,"saved_model"))
print(str(model_name)+" loaded....")

ssd_mobilenet_v2_320x320_coco17_tpu-8 loaded....


In [67]:
#Predict image class
image_path="test/5.jpg"
image=cv2.imread(image_path)
#image=cv2.resize(image,[400,600])
"""cv2.imshow("input image",image)
cv2.waitKey(0)
cv2.destroyAllWindows()"""

'cv2.imshow("input image",image)\ncv2.waitKey(0)\ncv2.destroyAllWindows()'

In [18]:
type(image)

numpy.ndarray

In [68]:
image_np=cv2.cvtColor(image.copy(),cv2.COLOR_BGR2RGB)
image_tensor=tf.convert_to_tensor(image_np,dtype=tf.uint8)
image_tensor=image_tensor[tf.newaxis,...]

In [20]:
image_tensor

<tf.Tensor: shape=(1, 300, 500, 3), dtype=uint8, numpy=
array([[[[ 22,  24,  21],
         [ 23,  25,  22],
         [ 24,  26,  23],
         ...,
         [ 42,  38,  35],
         [ 43,  39,  37],
         [ 44,  40,  37]],

        [[ 22,  24,  21],
         [ 23,  25,  22],
         [ 24,  26,  23],
         ...,
         [ 43,  39,  36],
         [ 42,  38,  35],
         [ 42,  38,  36]],

        [[ 25,  27,  26],
         [ 24,  26,  25],
         [ 23,  25,  24],
         ...,
         [ 41,  37,  34],
         [ 41,  37,  34],
         [ 42,  38,  35]],

        ...,

        [[ 77, 112,  78],
         [ 59,  93,  59],
         [ 73, 108,  75],
         ...,
         [ 94, 132,  83],
         [ 81, 120,  68],
         [ 94, 133,  88]],

        [[ 79, 114,  80],
         [ 84, 117,  85],
         [ 69, 100,  68],
         ...,
         [ 71, 110,  64],
         [ 61, 100,  51],
         [ 74, 114,  67]],

        [[ 73, 110,  72],
         [ 87, 124,  83],
         [ 72, 108

In [21]:
image_tensor.shape

TensorShape([1, 300, 500, 3])

In [69]:
detections=tfod_model(image_tensor)
detections

{'raw_detection_boxes': <tf.Tensor: shape=(1, 1917, 4), dtype=float32, numpy=
 array([[[ 0.00665513,  0.01541594,  0.04255591,  0.04506221],
         [-0.01387352, -0.05932656,  0.08128764,  0.1835892 ],
         [-0.05385103, -0.02726308,  0.1687476 ,  0.08103043],
         ...,
         [ 0.18569553, -0.03737658,  0.7681482 ,  1.0284519 ],
         [-0.04374757,  0.19347847,  1.0101936 ,  0.7826912 ],
         [ 0.06276438,  0.01865673,  0.82680345,  0.9031202 ]]],
       dtype=float32)>,
 'detection_scores': <tf.Tensor: shape=(1, 100), dtype=float32, numpy=
 array([[0.7333708 , 0.7095722 , 0.68964374, 0.673481  , 0.6621213 ,
         0.646728  , 0.6302084 , 0.57311577, 0.57217276, 0.56662536,
         0.55531645, 0.5297367 , 0.5286741 , 0.52617145, 0.52171427,
         0.5182619 , 0.51644397, 0.5149955 , 0.5090414 , 0.505102  ,
         0.50304246, 0.5018595 , 0.4953852 , 0.49100596, 0.48620173,
         0.47000104, 0.46994993, 0.45907065, 0.45728946, 0.45573995,
         0.4512805 

In [24]:
detections.keys()

dict_keys(['raw_detection_boxes', 'detection_scores', 'detection_anchor_indices', 'num_detections', 'detection_classes', 'detection_multiclass_scores', 'raw_detection_scores', 'detection_boxes'])

In [25]:
detections['detection_classes']

<tf.Tensor: shape=(1, 100), dtype=float32, numpy=
array([[ 1.,  1., 37.,  1., 37., 40., 37., 40., 40., 40., 37., 43., 37.,
        40., 40., 43., 40., 37., 37., 37.,  1.,  1.,  1.,  1., 62.,  1.,
        37., 39., 62., 34., 37., 37., 37.,  1., 40.,  1., 40., 43., 43.,
        37.,  1., 15., 34., 40.,  1., 37., 40., 43.,  1., 34., 34.,  1.,
        62., 37.,  1.,  1., 37., 37.,  1.,  1., 62.,  1., 43., 37., 37.,
         1., 39.,  1., 15., 40.,  1., 15., 37., 40., 44., 39., 43.,  1.,
        37., 39., 39., 39., 40., 62., 40.,  1., 43.,  3., 39., 39., 39.,
         1., 43., 34.,  1., 62.,  1., 15.,  1.,  3.]], dtype=float32)>

In [29]:
detections['detection_classes'][0]

<tf.Tensor: shape=(100,), dtype=float32, numpy=
array([ 1.,  1., 37.,  1., 37., 40., 37., 40., 40., 40., 37., 43., 37.,
       40., 40., 43., 40., 37., 37., 37.,  1.,  1.,  1.,  1., 62.,  1.,
       37., 39., 62., 34., 37., 37., 37.,  1., 40.,  1., 40., 43., 43.,
       37.,  1., 15., 34., 40.,  1., 37., 40., 43.,  1., 34., 34.,  1.,
       62., 37.,  1.,  1., 37., 37.,  1.,  1., 62.,  1., 43., 37., 37.,
        1., 39.,  1., 15., 40.,  1., 15., 37., 40., 44., 39., 43.,  1.,
       37., 39., 39., 39., 40., 62., 40.,  1., 43.,  3., 39., 39., 39.,
        1., 43., 34.,  1., 62.,  1., 15.,  1.,  3.], dtype=float32)>

In [26]:
detections['num_detections']

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([100.], dtype=float32)>

In [27]:
detections['detection_multiclass_scores']

<tf.Tensor: shape=(1, 100, 91), dtype=float32, numpy=
array([[[0.00726716, 0.8431642 , 0.01011081, ..., 0.03229116,
         0.00969887, 0.01592432],
        [0.0033946 , 0.69100046, 0.02195593, ..., 0.02139076,
         0.00886536, 0.019387  ],
        [0.00336055, 0.03044738, 0.01543558, ..., 0.02691819,
         0.02153449, 0.01904144],
        ...,
        [0.00374085, 0.1333712 , 0.0184877 , ..., 0.00588361,
         0.00306697, 0.00546343],
        [0.0035945 , 0.1172737 , 0.03926898, ..., 0.00923891,
         0.00379152, 0.01743363],
        [0.00351983, 0.14236192, 0.04045882, ..., 0.01271584,
         0.01139199, 0.02067576]]], dtype=float32)>

In [28]:
detections['detection_boxes']

<tf.Tensor: shape=(1, 100, 4), dtype=float32, numpy=
array([[[0.05321816, 0.18361409, 0.9249048 , 0.6604728 ],
        [0.11706181, 0.69319135, 0.47746843, 0.7701675 ],
        [0.7804989 , 0.54135114, 0.9206938 , 0.6350711 ],
        [0.11570881, 0.5205772 , 0.23051707, 0.58787966],
        [0.8860309 , 0.53045595, 0.93733037, 0.5861584 ],
        [0.24273989, 0.17895274, 0.31488934, 0.2559789 ],
        [0.7938413 , 0.5200024 , 0.9264174 , 0.60358876],
        [0.30990237, 0.73467964, 0.38846982, 0.76475745],
        [0.25354686, 0.18461053, 0.3172913 , 0.22875984],
        [0.3256724 , 0.7206318 , 0.3798275 , 0.7434451 ],
        [0.77946776, 0.5287789 , 0.89317733, 0.59700835],
        [0.25354686, 0.18461053, 0.3172913 , 0.22875984],
        [0.41912523, 0.62630075, 0.47050378, 0.6661069 ],
        [0.41912523, 0.62630075, 0.47050378, 0.6661069 ],
        [0.33833423, 0.72549266, 0.43545094, 0.7664406 ],
        [0.24273989, 0.17895274, 0.31488934, 0.2559789 ],
        [0.33631298

In [30]:
detections['detection_boxes'][0]

<tf.Tensor: shape=(100, 4), dtype=float32, numpy=
array([[0.05321816, 0.18361409, 0.9249048 , 0.6604728 ],
       [0.11706181, 0.69319135, 0.47746843, 0.7701675 ],
       [0.7804989 , 0.54135114, 0.9206938 , 0.6350711 ],
       [0.11570881, 0.5205772 , 0.23051707, 0.58787966],
       [0.8860309 , 0.53045595, 0.93733037, 0.5861584 ],
       [0.24273989, 0.17895274, 0.31488934, 0.2559789 ],
       [0.7938413 , 0.5200024 , 0.9264174 , 0.60358876],
       [0.30990237, 0.73467964, 0.38846982, 0.76475745],
       [0.25354686, 0.18461053, 0.3172913 , 0.22875984],
       [0.3256724 , 0.7206318 , 0.3798275 , 0.7434451 ],
       [0.77946776, 0.5287789 , 0.89317733, 0.59700835],
       [0.25354686, 0.18461053, 0.3172913 , 0.22875984],
       [0.41912523, 0.62630075, 0.47050378, 0.6661069 ],
       [0.41912523, 0.62630075, 0.47050378, 0.6661069 ],
       [0.33833423, 0.72549266, 0.43545094, 0.7664406 ],
       [0.24273989, 0.17895274, 0.31488934, 0.2559789 ],
       [0.33631298, 0.7171725 , 0.4527

In [31]:
bboxs=detections['detection_boxes'][0].numpy()
bboxs

array([[0.05321816, 0.18361409, 0.9249048 , 0.6604728 ],
       [0.11706181, 0.69319135, 0.47746843, 0.7701675 ],
       [0.7804989 , 0.54135114, 0.9206938 , 0.6350711 ],
       [0.11570881, 0.5205772 , 0.23051707, 0.58787966],
       [0.8860309 , 0.53045595, 0.93733037, 0.5861584 ],
       [0.24273989, 0.17895274, 0.31488934, 0.2559789 ],
       [0.7938413 , 0.5200024 , 0.9264174 , 0.60358876],
       [0.30990237, 0.73467964, 0.38846982, 0.76475745],
       [0.25354686, 0.18461053, 0.3172913 , 0.22875984],
       [0.3256724 , 0.7206318 , 0.3798275 , 0.7434451 ],
       [0.77946776, 0.5287789 , 0.89317733, 0.59700835],
       [0.25354686, 0.18461053, 0.3172913 , 0.22875984],
       [0.41912523, 0.62630075, 0.47050378, 0.6661069 ],
       [0.41912523, 0.62630075, 0.47050378, 0.6661069 ],
       [0.33833423, 0.72549266, 0.43545094, 0.7664406 ],
       [0.24273989, 0.17895274, 0.31488934, 0.2559789 ],
       [0.33631298, 0.7171725 , 0.45274755, 0.75262654],
       [0.3256724 , 0.7206318 ,

In [32]:
class_indexes=detections['detection_classes'][0].numpy().astype(np.int32)
class_indexes

array([ 1,  1, 37,  1, 37, 40, 37, 40, 40, 40, 37, 43, 37, 40, 40, 43, 40,
       37, 37, 37,  1,  1,  1,  1, 62,  1, 37, 39, 62, 34, 37, 37, 37,  1,
       40,  1, 40, 43, 43, 37,  1, 15, 34, 40,  1, 37, 40, 43,  1, 34, 34,
        1, 62, 37,  1,  1, 37, 37,  1,  1, 62,  1, 43, 37, 37,  1, 39,  1,
       15, 40,  1, 15, 37, 40, 44, 39, 43,  1, 37, 39, 39, 39, 40, 62, 40,
        1, 43,  3, 39, 39, 39,  1, 43, 34,  1, 62,  1, 15,  1,  3])

In [33]:
class_scores=detections['detection_scores'][0].numpy()
class_scores

array([0.8431642 , 0.69100046, 0.49936628, 0.43420446, 0.40773296,
       0.40102836, 0.36907464, 0.35119942, 0.3356873 , 0.33289638,
       0.29368615, 0.26663542, 0.25641072, 0.25492895, 0.24436477,
       0.239276  , 0.2368813 , 0.2355312 , 0.22446306, 0.21982577,
       0.21905354, 0.21530214, 0.19934398, 0.19479999, 0.18573423,
       0.18168972, 0.18158057, 0.1800841 , 0.1780555 , 0.1774834 ,
       0.16925283, 0.16908155, 0.16891767, 0.16687936, 0.16396052,
       0.16387825, 0.16184424, 0.1615867 , 0.16108774, 0.15880126,
       0.1568168 , 0.15580899, 0.15339781, 0.15280543, 0.15249121,
       0.1480709 , 0.1477621 , 0.14688359, 0.14658454, 0.1454181 ,
       0.14504498, 0.14236192, 0.1421257 , 0.14142092, 0.14130177,
       0.14011478, 0.13969906, 0.13937555, 0.13844705, 0.13813412,
       0.13744019, 0.13684049, 0.13664371, 0.13598086, 0.13375627,
       0.1333712 , 0.13289516, 0.13267782, 0.13161619, 0.13159305,
       0.131375  , 0.13033697, 0.12987356, 0.12953782, 0.12936

In [55]:
iH,iW,iC=image.shape

In [56]:
iH,iW,iC

(300, 500, 3)

In [36]:
#code for 1st (single) detedcted object

In [38]:
bboxs.shape

(100, 4)

In [39]:
bboxs[0]

array([0.05321816, 0.18361409, 0.9249048 , 0.6604728 ], dtype=float32)

In [40]:
class_indexes[0]

1

In [41]:
class_scores[0]

0.8431642

In [42]:
display_text=class_list[class_indexes[0]]
display_text

'person'

In [44]:
class_color=color_list[class_indexes[0]]

In [48]:
#get values of bbox
#below values are normalised x,y cordinates
ymin,xmin,ymax,xmax=bboxs[0]
#converting them to actual x,y values
xmin,xmax,ymin,ymax=(xmin*iW,xmax*iW,ymin*iH,ymax*iH)
#converting flaot to int
xmin,xmax,ymin,ymax=int(xmin),int(xmax),int(ymin),int(ymax)

In [49]:
xmin,xmax,ymin,ymax

(91, 330, 15, 277)

In [50]:
cv2.rectangle(image,(xmin,ymin),(xmax,ymax), color=class_color,thickness=2)
cv2.putText(image,display_text,(20,20),cv2.FONT_HERSHEY_COMPLEX,1,class_color,1)
cv2.imwrite("p1.jpg",image)

True

In [72]:
#bbox_idx=tf.image.non_max_supression(bboxs,class_scores,max_output_size=50,iou_treshold=0.5,score_threshold=0.5)

#if bbox is found i.e. object is detected
if len(bboxs)!=0:
    for i in range(0,len(bboxs)):
        bbox=tuple(bboxs[i].tolist())
        class_confidence=round(100*class_scores[i])
        class_index=class_indexes[i]
        
        if class_confidence>50.0:            
            print("class_confidence--",class_confidence)
            class_lbl_txt=class_list[class_index]
            class_color=color_list[class_index]

            display_text=str(class_lbl_txt)+" "+str(class_confidence)

            #get values of bbox
            #below values are normalised x,y cordinates
            ymin,xmin,ymax,xmax=bbox
            #converting them to actual x,y values
            xmin,xmax,ymin,ymax=(xmin*iW,xmax*iW,ymin*iH,ymax*iH)
            #converting flaot to int
            xmin,xmax,ymin,ymax=int(xmin),int(xmax),int(ymin),int(ymax)

            cv2.rectangle(image,(xmin,ymin),(xmax,ymax), color=class_color,thickness=2)
            cv2.putText(image,display_text,(xmin,ymin-10),cv2.FONT_HERSHEY_PLAIN,1,class_color,2)

    #cv2.imshow("result",image)
    cv2.imwrite("p5.jpg",image)

class_confidence-- 84
class_confidence-- 69
